MAP = {
 "部分滤除仍须进入结论": ["tests.test_weekly_digest.PartialFilterDisclosureTest.test_partial_filtering_is_disclosed_even_when_items_kept"],
 "采到的条目全部发布于区间外": ["tests.test_weekly_digest.PartialFilterDisclosureTest.test_kept_items_all_outside_window_is_not_confirmed_zero",
                    "tests.test_weekly_digest.PartialFilterDisclosureTest.test_pure_gdelt_entry_outside_window_is_not_confirmed_zero"],
 "源返回的元素结构不可识别": ["tests.test_events.RawCountTest.test_fetch_counts_malformed_elements_end_to_end",
                 "tests.test_weekly_digest.LegacySnapshotCapParityTest.test_collector_dropped_malformed_blocks_zero_claim"],
 "同一次截断不得记两遍": ["tests.test_weekly_digest.MainChannelCapDisclosureTest.test_pure_gnews_day_counts_one_truncation_not_two"],
 "不过滤的通道不得重复披露同一次截断": ["tests.test_weekly_digest.LegacySnapshotCapParityTest.test_pure_gdelt_truncation_disclosed_once"],
 "去重后未触顶不算条数被钉住": ["tests.test_events.RawCountTest.test_count_at_cap_excludes_deduped_duplicates"],
 "主通道跑失败不得读作确实为零": ["tests.test_weekly_digest.LegacySnapshotCapParityTest.test_main_channel_failure_blocks_the_zero_claim"],
 "第二次截断由脚本判定": ["tests.test_derive.SampleCappedTest.test_main_sample_capped_is_not_key_presence"],
 "未触顶日不得稀释结论句里的上限": ["tests.test_weekly_digest.LegacySnapshotCapParityTest.test_untruncated_day_does_not_dilute_the_cap_in_the_verdict"],
 "元素全部不可识别时记为缺漏": ["tests.test_events.RawCountTest.test_malformed_elements_are_counted_into_the_snapshot",
                  "tests.test_events.RawCountTest.test_partial_malformed_drop_is_not_a_gap"],
 "主通道未启用时可署名来源标志不为空值": ["tests.test_events.ReviewRoundTwoTest.test_attributable_flag_false_when_main_channel_disabled"],
 "两条通道都没跑成时可署名来源标志为空值": ["tests.test_events.ReviewRoundTwoTest.test_attributable_flag_null_only_when_nothing_collected"],
 "主通道截断不得污染条数触顶标志": ["tests.test_derive.SampleCappedTest.test_main_channel_truncation_does_not_pollute_count_capped"],
 "两条通道都没采到时不得计为已采集": ["tests.test_events.ObservationGapTest.test_both_channels_fail_articles_is_null_not_empty_list"],
 "整区间被相关性闸门滤空": ["tests.test_weekly_digest.DroppedDayInvariantTest.test_offlist_layer_still_blocks_zero_claim"],
 "区间内上限不唯一": ["tests.test_weekly_digest.LegacySnapshotCapParityTest.test_untruncated_day_does_not_dilute_the_cap_in_the_verdict"],
 "补位不得抹掉主通道的截断事实": ["tests.test_events.TwoPassCollectTest.test_backfill_keeps_gnews_filter_counts",
                   "tests.test_weekly_digest.LegacySnapshotCapParityTest.test_backfill_day_discloses_both_truncations"],
 "可署名来源缺席由脚本判定": ["tests.test_events.ReviewRoundTwoTest.test_attributable_source_absent_only_when_nothing_usable",
                 "tests.test_events.ReviewRoundTwoTest.test_attributable_flag_false_when_gdelt_backfilled"],
 "跨通道不给差值": ["tests.test_derive.ChannelOfEdgeTest.test_switch_from_empty_gnews_day_refuses_delta"],
 "时间戳格式跨通道一致": ["tests.test_events.GnewsFilterTest.test_seendate_uses_gdelt_format_not_iso",
                "tests.test_events.GnewsFilterTest.test_seendate_is_parseable_by_weekly_digest"],
 "正常采集": ["tests.test_events.GnewsOneTest.test_entry_shape_and_channel"],
 "主通道条目被相关性闸门滤除": ["tests.test_events.GnewsOneTest.test_offlist_items_counted_not_dropped_silently"],
 "相关性闸门滤空后 GDELT 补位": ["tests.test_events.TwoPassCollectTest.test_all_filtered_out_triggers_gdelt_backfill"],
 "两条通道都无所得": ["tests.test_events.TwoPassCollectTest.test_both_channels_fail_gap_mentions_both"],
 "白名单匹配不得误命中相似域名": ["tests.test_events.WhitelistTest.test_suffix_lookalike_must_not_match"],
 "白名单收录子域": ["tests.test_events.WhitelistTest.test_subdomain_matches"],
 "服务端时间窗不可信": ["tests.test_events.GnewsFilterTest.test_only_in_window_on_list_survives",
              "tests.test_events.GnewsFilterTest.test_boundary_timestamps_are_inclusive"],
 "发布时间不可解析": ["tests.test_events.GnewsRobustnessTest.test_item_without_pubdate_counted_undated"],
 "源返回条数顶到上限": ["tests.test_events.GnewsOneTest.test_capped_at_soft_cap_99",
               "tests.test_events.GnewsOneTest.test_not_capped_at_98"],
 "主通道未配置": ["tests.test_events.WhitelistLoadTest.test_unconfigured_is_silent_disable",
             "tests.test_events.TwoPassCollectTest.test_gnews_unconfigured_falls_back_to_gdelt_only"],
 "主通道响应畸形": ["tests.test_events.GnewsParseTest.test_non_xml_raises_not_empty_list",
              "tests.test_events.TwoPassCollectTest.test_gnews_parse_failure_records_gap_and_backfills"],
 "限速软失败退避": ["tests.test_events.EventsTest.test_soft_rate_limit_retry_succeeds"],
 "硬限流退避": ["tests.test_events.HardRateLimitTest.test_hard_429_retry_succeeds",
            "tests.test_events.HardRateLimitTest.test_hard_429_persistent_becomes_gap"],
 "查询顺序轮转": ["tests.test_events.QueryOrderTest.test_order_is_a_rotation_of_all_currencies",
             "tests.test_events.QueryOrderTest.test_collect_follows_rotated_order"],
 "标题去重": ["tests.test_events.DedupeTest.test_duplicate_titles_collapsed",
           "tests.test_events.GnewsOneTest.test_dedupe_runs_after_whitelist"],
 "端点不可用": ["tests.test_events.EventsTest.test_endpoint_error_single_currency"],
}
