#!/usr/bin/env python3
"""趋势块生成器 —— 报告「## 趋势」节与趋势序列的**唯一事实源**。

存在理由:日报只看当日、周报只看当周,读者拿不到"这条线走了多久、走到哪儿"
这一层。补这一层的自然做法是让 LLM 回看几份旧报告再总结 —— 而本仓库的
数字纪律恰恰禁止这一件事:报告里的数只准逐字抄当日快照与要点表,跨日比较
一旦经手 LLM,就是无源的心算。

所以趋势与附录 A 同规格:**整块由脚本生成,LLM 一个字符都不写**,校验端
的判据是「报告逐字包含整块」。三条硬性质,与 `scripts/appendix.py` 同源:

1. **锚点字面量只在这里写一份**,`scripts/check_report.py` 只许 import。
2. **确定性**:同一输入逐字节相同 —— 币种序取固定表、日期排序后输出、
   数值走 `appendix.num_text` 这一个格式化口(不另建第二个)。
3. **纯函数 + 薄 CLI**:导入期不读文件、不解析 argv。

**本模块只转录与排序,不判定**:方向由两次定盘的**比较**给出(不做减法,
浮点差值会在末位造出假精度),复盘档位取 `weekly_digest.VERDICTS`
(唯一事实源),不在这里另抄一份档名。
"""
import argparse
import json
import os
import re
import sys

try:                                                 # pragma: no cover - 包内分支
    from scripts.appendix import num_text
    from scripts.weekly_digest import VERDICTS, UNREVIEWED
except ImportError:                                  # pragma: no cover - 直跑分支
    from appendix import num_text
    from weekly_digest import VERDICTS, UNREVIEWED

# ---- 趋势节锚点:产出方拥有,校验端只许 import ----
TREND_ANCHOR = "## 趋势(scripts/trend.py 生成,勿手改)"
TREND_ANCHOR_EN = ("## Trend (generated by scripts/trend.py; "
                   "do not hand-edit)")
# 有定盘序列的四条。USD 是基准货币,`derived.rates` 里没有它的条目 ——
# 把它列进来只会得到一行"无读数",那是格式噪声,不是信息。
PAIR_CURRENCIES = ("EUR", "PHP", "THB", "BRL")
# 经济体序按实际利率排序时才定;这张表只管**码 → 名**,且两种语言各一份。
ECONOMY_NAME = {"US": "美国", "EA": "欧元区", "PH": "菲律宾",
                "TH": "泰国", "BR": "巴西"}
ECONOMY_NAME_EN = {"US": "United States", "EA": "Euro area",
                   "PH": "Philippines", "TH": "Thailand", "BR": "Brazil"}
CURRENCY_ECONOMY = {"EUR": "EA", "PHP": "PH", "THB": "TH", "BRL": "BR",
                    "USD": "US"}
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
WEEK_RE = re.compile(r"^\d{4}-W\d{2}$")
CHAIN_MAX = 5          # 定盘链最多回溯几次,长了读者只会跳过
NO_SERIES = "该序列本窗口内无读数"
NO_SERIES_EN = "no readings in this window"


# ------------------------------------------------------------------ 载入

def _read_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_snapshots(data_dir, upto=None):
    """`data/` 下的快照,按日期升序;`upto` 给定时只取不晚于它的。

    坏文件**跳过而不静默**:返回的第二个元素是跳过清单,调用方要么打印
    要么带进 payload —— 悄悄少一天会让"连续 N 次"少算一截,而少算这件事
    在输出上与"确实没走那么久"完全同形。
    """
    good, skipped = [], []
    try:
        names = sorted(os.listdir(data_dir))
    except OSError as e:
        return [], ["%s: %s" % (data_dir, e)]
    for name in names:
        if not name.endswith(".json"):
            continue
        stem = name[:-5]
        if not DATE_RE.match(stem) or (upto is not None and stem > upto):
            continue
        try:
            payload = _read_json(os.path.join(data_dir, name))
        except (OSError, UnicodeDecodeError, ValueError, RecursionError) as e:
            skipped.append("%s: %s" % (name, e))
            continue
        if isinstance(payload, dict):
            good.append((stem, payload))
        else:
            skipped.append("%s: 顶层不是对象" % name)
    return good, skipped


def load_digests(state_dir, upto_week=None):
    """`state/weekly-digest-*.json`,按周号升序。"""
    out = []
    try:
        names = sorted(os.listdir(state_dir))
    except OSError:
        return out
    for name in names:
        m = re.fullmatch(r"weekly-digest-(\d{4}-W\d{2})\.json", name)
        if not m or (upto_week is not None and m.group(1) > upto_week):
            continue
        try:
            payload = _read_json(os.path.join(state_dir, name))
        except (OSError, UnicodeDecodeError, ValueError, RecursionError):
            continue
        if isinstance(payload, dict):
            out.append((m.group(1), payload))
    return out


def load_decisions(path, upto=None):
    out = []
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except ValueError:
                    continue
                if not isinstance(row, dict):
                    continue
                d = row.get("date")
                if not isinstance(d, str) or (upto is not None and d > upto):
                    continue
                out.append(row)
    except OSError:
        return []
    return out


# ------------------------------------------------ 序列(只转录,不判定)

def _slice(snap, *keys):
    cur = snap
    for k in keys:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(k)
    return cur


def fixing_series(snapshots, currency):
    """定盘序列 [(ref_date, primary)],按定盘日升序、同一定盘日只留一条。

    以 `ref_date` 而不是快照日为键:周一那份快照报的是上周五的定盘,按快照日
    排会把同一次定盘数成两次,"连续 N 次"随之虚高。同一定盘日出现两个值时
    取**后一份快照**的值(重采修正了前一份)。
    """
    by_ref = {}
    for _date, snap in snapshots:
        row = _slice(snap, "rates", currency)
        if not isinstance(row, dict):
            continue
        ref, primary = row.get("ref_date"), row.get("primary")
        if not isinstance(ref, str) or isinstance(primary, bool):
            continue
        if not isinstance(primary, (int, float)):
            continue
        by_ref[ref] = primary
    return [(r, by_ref[r]) for r in sorted(by_ref)]


def trailing_run(series):
    """末尾连续同向的**次数**与方向:(n, "weak"|"strong"|"flat")。

    方向只由比较给出,不做减法 —— 浮点差值会在末位造出假精度,而这个数
    要印进报告。序列不足两点时返回 (0, "flat")。
    """
    if len(series) < 2:
        return 0, "flat"
    def sign(a, b):
        return "weak" if b > a else ("strong" if b < a else "flat")
    last = sign(series[-2][1], series[-1][1])
    n = 1
    for i in range(len(series) - 2, 0, -1):
        if sign(series[i - 1][1], series[i][1]) != last:
            break
        n += 1
    return n, last


def real_rate_series(snapshots, economy):
    """实际利率序列 [(快照日, value)],按快照日升序、值缺失的日子不进序列。"""
    out = []
    for date, snap in snapshots:
        row = _slice(snap, "derived", "real_rate", economy)
        if not isinstance(row, dict):
            continue
        v = row.get("value")
        if isinstance(v, bool) or not isinstance(v, (int, float)):
            continue
        out.append((date, v))
    return out


def verdict_counts(rows):
    """决策日志按复盘档位计数。档名取 `weekly_digest.VERDICTS`,不另抄一份。"""
    counts = {k: 0 for k in VERDICTS}
    for row in rows:
        status = _slice(row, "review", "status")
        key = status if isinstance(status, str) and status in counts else UNREVIEWED
        counts[key] += 1
    return counts


# ------------------------------------------------------------------ 成块

def _chain(series, lang):
    tail = series[-CHAIN_MAX:]
    sep = " → "
    return sep.join("%s(%s)" % (num_text(v), r) if lang == "zh"
                    else "%s (%s)" % (num_text(v), r) for r, v in tail)


def _run_phrase(n, direction, lang):
    if n <= 0:
        return None
    if direction == "flat":
        return ("最近一次与上一次定盘持平" if lang == "zh"
                else "latest fixing unchanged from the previous one")
    if lang == "zh":
        return "最近连续 %d 次朝美元%s" % (n, "走弱" if direction == "weak"
                                          else "走强")
    return ("weakened against the dollar %d fixings running" % n
            if direction == "weak"
            else "strengthened against the dollar %d fixings running" % n)


def _band_phrase(primary, low, high, lang):
    """当次定盘在 5 运行日区间里的位置。只用比较,不算百分位。"""
    if primary is None or low is None or high is None:
        return None
    if primary >= high:
        where = "上沿" if lang == "zh" else "at the top of"
    elif primary <= low:
        where = "下沿" if lang == "zh" else "at the bottom of"
    else:
        where = "区间内" if lang == "zh" else "inside"
    if lang == "zh":
        return "当次贴在 5 运行日区间 %s–%s 的%s" % (
            num_text(low), num_text(high), where)
    return "sits %s the 5-running-day band %s–%s" % (
        where, num_text(low), num_text(high))


def _num_or_none(v):
    return None if isinstance(v, bool) or not isinstance(v, (int, float)) else v


def daily_trend(snapshots, decisions, date, lang="zh"):
    """日报「## 趋势」整块。`snapshots` 须已按日期升序且不晚于 `date`。"""
    zh = lang == "zh"
    lines = [TREND_ANCHOR if zh else TREND_ANCHOR_EN, ""]
    dates = [d for d, _ in snapshots]
    if dates:
        lines.append(("- 观察窗:%s 至 %s,共 %d 份日度读数" % (
            dates[0], dates[-1], len(dates))) if zh else
            ("- Window: %s to %s, %d daily readings" % (
                dates[0], dates[-1], len(dates))))
    latest = snapshots[-1][1] if snapshots else {}
    for ccy in PAIR_CURRENCIES:
        series = fixing_series(snapshots, ccy)
        if not series:
            lines.append("- %s:%s" % (ccy, NO_SERIES) if zh
                         else "- %s: %s" % (ccy, NO_SERIES_EN))
            continue
        parts = [("近 %d 次定盘 %s" % (len(series[-CHAIN_MAX:]),
                                      _chain(series, lang))) if zh
                 else ("last %d fixings %s" % (len(series[-CHAIN_MAX:]),
                                               _chain(series, lang)))]
        run = _run_phrase(*trailing_run(series), lang=lang)
        if run:
            parts.append(run)
        drow = _slice(latest, "derived", "rates", ccy)
        band = _band_phrase(
            series[-1][1],
            _num_or_none(drow.get("range_5d_low")) if isinstance(drow, dict) else None,
            _num_or_none(drow.get("range_5d_high")) if isinstance(drow, dict) else None,
            lang)
        if band:
            parts.append(band)
        lines.append("- %s:%s" % (ccy, ";".join(parts)) if zh
                     else "- %s: %s" % (ccy, "; ".join(parts)))
    lines.append(_real_rate_line(snapshots, lang))
    counts = verdict_counts(decisions)
    total = sum(counts.values())
    body = ("、".join("%s %d" % (k, counts[k]) for k in VERDICTS) if zh
            else ", ".join("%s %d" % (k, counts[k]) for k in VERDICTS))
    # 措辞刻意写成「登记于 … 及之前」+「按最新复盘结果」:计数只筛登记日,
    # 而每条的档位是**复盘那天**才定的。回填一份旧日报时,若写成"截至那天
    # 的战绩",读者会以为那些命中在那天已经成立 —— 那是拿后来的知识去装点
    # 当时的判断,与本仓禁止的"事后叙述"是同一件事。
    lines.append(("- 观点分布(登记于 %s 及之前的 %d 条,按最新复盘结果):%s"
                  % (date, total, body)) if zh else
                 ("- Calls registered through %s (%d in total, "
                  "by latest review outcome): %s" % (date, total, body)))
    return "\n".join(lines)


def _unchanged_run(series):
    """末尾有多少份读数与最新一份**相等**(含最新那份本身)。

    刻意不报"自窗口起点以来的变化":实际利率的分母是 CPI,而本仓库
    2026-08-11 换过 CPI 口径(IMF 镜像 → BLS,期号前移 11 个月),窗口两端
    相减得到的"上移/下移"里混着口径差。跨口径的差不是行情,把它印成趋势
    正是禁令 5 点名的那种错误。相等这件事不受口径影响,报它才是安全的。
    """
    if not series:
        return 0
    last, n = series[-1][1], 1
    for i in range(len(series) - 2, -1, -1):
        if series[i][1] != last:
            break
        n += 1
    return n


def _real_rate_line(snapshots, lang):
    zh = lang == "zh"
    names = ECONOMY_NAME if zh else ECONOMY_NAME_EN
    rows = []
    for econ in ECONOMY_NAME:
        series = real_rate_series(snapshots, econ)
        if not series:
            continue
        n = _unchanged_run(series)
        if n >= 2:
            note = "连续 %d 份读数未变" % n if zh \
                else "unchanged across %d readings" % n
        else:
            note = "本份读数为新值" if zh else "new reading this run"
        rows.append((series[-1][1], names[econ], num_text(series[-1][1]), note))
    if not rows:
        return "- 实际利率:%s" % NO_SERIES if zh \
            else "- Real rates: %s" % NO_SERIES_EN
    rows.sort(key=lambda r: (-r[0], r[1]))
    body = ("、".join("%s %s(%s)" % (n, v, m) for _, n, v, m in rows) if zh
            else ", ".join("%s %s (%s)" % (n, v, m) for _, n, v, m in rows))
    return ("- 实际利率(高→低):%s" % body) if zh \
        else ("- Real rates (high to low): %s" % body)


def weekly_trend(digests, week, lang="zh"):
    """周报「## 趋势」整块。`digests` 是 [(周号, payload)],升序、不晚于 `week`。"""
    zh = lang == "zh"
    lines = [TREND_ANCHOR if zh else TREND_ANCHOR_EN, ""]
    weeks = [w for w, _ in digests]
    if weeks:
        lines.append(("- 观察窗:%s 至 %s,共 %d 周" % (weeks[0], weeks[-1],
                                                     len(weeks))) if zh
                     else ("- Window: %s to %s, %d weeks"
                           % (weeks[0], weeks[-1], len(weeks))))
    for ccy in PAIR_CURRENCIES:
        chg, band = [], None
        for w, payload in digests:
            row = _slice(payload, "rates", ccy)
            if not isinstance(row, dict):
                continue
            v = _num_or_none(row.get("chg_pct_week"))
            if v is not None:
                chg.append("%s %s%%" % (w, num_text(v)))
            lo, hi = _num_or_none(row.get("range_low")), \
                _num_or_none(row.get("range_high"))
            if lo is not None and hi is not None:
                band = (w, lo, hi)
        if not chg and band is None:
            lines.append("- %s:%s" % (ccy, NO_SERIES) if zh
                         else "- %s: %s" % (ccy, NO_SERIES_EN))
            continue
        parts = []
        if chg:
            parts.append(("周变动 %s" % " → ".join(chg)) if zh
                         else ("weekly change %s" % " → ".join(chg)))
        if band:
            parts.append(("%s 区间 %s–%s" % (band[0], num_text(band[1]),
                                             num_text(band[2]))) if zh
                         else ("%s band %s–%s" % (band[0], num_text(band[1]),
                                                  num_text(band[2]))))
        lines.append("- %s:%s" % (ccy, ";".join(parts)) if zh
                     else "- %s: %s" % (ccy, "; ".join(parts)))
    for w, payload in digests:
        counts = payload.get("verdicts")
        if not isinstance(counts, dict):
            continue
        body = ("、".join("%s %s" % (k, num_text(counts.get(k)))
                          for k in VERDICTS) if zh
                else ", ".join("%s %s" % (k, num_text(counts.get(k)))
                               for k in VERDICTS))
        lines.append("- %s 复盘:%s" % (w, body) if zh
                     else "- %s review: %s" % (w, body))
    lines.append("- 本块对应周号:%s" % week if zh
                 else "- Week covered by this block: %s" % week)
    return "\n".join(lines)


# ------------------------------------------------------- 序列(给可视化用)

def series_payload(snapshots, decisions, digests, skipped=()):
    """趋势序列 JSON。**所有聚合在这里算完**,消费端只负责画,不再算第二遍。"""
    return {
        "generated_from": [d for d, _ in snapshots],
        "skipped": list(skipped),
        "fixings": {
            ccy: [{"ref_date": r, "primary": v}
                  for r, v in fixing_series(snapshots, ccy)]
            for ccy in PAIR_CURRENCIES},
        "bands": {
            ccy: [{"date": d,
                   "low": _num_or_none((_slice(s, "derived", "rates", ccy)
                                        or {}).get("range_5d_low")),
                   "high": _num_or_none((_slice(s, "derived", "rates", ccy)
                                         or {}).get("range_5d_high")),
                   "chg_pct_1d": _num_or_none(
                       (_slice(s, "derived", "rates", ccy)
                        or {}).get("chg_pct_1d"))}
                  for d, s in snapshots]
            for ccy in PAIR_CURRENCIES},
        "real_rate": {
            econ: [{"date": d, "value": v}
                   for d, v in real_rate_series(snapshots, econ)]
            for econ in ECONOMY_NAME},
        "runs": {ccy: dict(zip(("n", "direction"),
                               trailing_run(fixing_series(snapshots, ccy))))
                 for ccy in PAIR_CURRENCIES},
        "verdict_totals": verdict_counts(decisions),
        "verdicts_by_date": _verdicts_by_date(decisions),
        "weekly": [{"week": w,
                    "rates": _weekly_rates(p),
                    "verdicts": p.get("verdicts")
                    if isinstance(p.get("verdicts"), dict) else None}
                   for w, p in digests],
        "economy_name": dict(ECONOMY_NAME),
        "currency_economy": dict(CURRENCY_ECONOMY),
        "verdict_order": list(VERDICTS),
    }


def _weekly_rates(payload):
    out = {}
    for ccy in PAIR_CURRENCIES:
        row = _slice(payload, "rates", ccy)
        if isinstance(row, dict):
            out[ccy] = {k: _num_or_none(row.get(k))
                        for k in ("chg_pct_week", "range_low", "range_high",
                                  "fixings", "days_observed")}
    return out


def _verdicts_by_date(decisions):
    by = {}
    for row in decisions:
        d = row.get("date")
        if not isinstance(d, str):
            continue
        status = _slice(row, "review", "status")
        key = status if isinstance(status, str) and status in VERDICTS \
            else UNREVIEWED
        by.setdefault(d, {k: 0 for k in VERDICTS})[key] += 1
    return {d: by[d] for d in sorted(by)}


# -------------------------------------------------------------------- 薄 CLI

def build_parser():
    ap = argparse.ArgumentParser(
        description="生成报告「## 趋势」整块,或导出趋势序列 JSON")
    ap.add_argument("--mode", required=True,
                    choices=("daily", "weekly", "series"))
    ap.add_argument("--date", help="日报模式:报告日期 YYYY-MM-DD")
    ap.add_argument("--week", help="周报模式:ISO 周号 YYYY-Www")
    ap.add_argument("--lang", default="zh", choices=("zh", "en"))
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--state-dir", default="state")
    ap.add_argument("--decision-log", default="state/decision-log.jsonl")
    return ap


def main(argv=None):
    args = build_parser().parse_args(argv)
    if args.mode == "daily" and not (args.date and DATE_RE.match(args.date)):
        print("--mode daily 需要 --date YYYY-MM-DD", file=sys.stderr)
        return 2
    if args.mode == "weekly" and not (args.week and WEEK_RE.match(args.week)):
        print("--mode weekly 需要 --week YYYY-Www", file=sys.stderr)
        return 2
    if args.mode == "weekly":
        digests = load_digests(args.state_dir, upto_week=args.week)
        if not digests:
            print("%s 之前没有周度聚合文件" % args.week, file=sys.stderr)
            return 2
        print(weekly_trend(digests, args.week, args.lang))
        return 0
    snapshots, skipped = load_snapshots(args.data_dir, upto=args.date)
    for s in skipped:
        print("跳过 %s" % s, file=sys.stderr)
    if not snapshots:
        print("%s 之前没有可读快照" % (args.date or "全窗口"), file=sys.stderr)
        return 2
    decisions = load_decisions(args.decision_log, upto=args.date)
    if args.mode == "daily":
        print(daily_trend(snapshots, decisions, args.date, args.lang))
        return 0
    digests = load_digests(args.state_dir)
    print(json.dumps(series_payload(snapshots, decisions, digests, skipped),
                     ensure_ascii=False, indent=1, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
